# Site Settings
title: Salutem
alt: img/logo.svg
tagline: Salutem
email: your-email@domain.com
description: >
  
baseurl: "/salutem"
url: ""
permalink: pretty

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "Posts"
    values:
      author: "Salutem"
      layout: post
      image: /img/home.png
      show_sidebar: true
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  -
    scope:
      path: ""
      type: "natures"
    values:
      layout: "nature"

  -
    scope:
      path: ""
      type: "news"
    values:
      author: "Salutem"
      layout: new
      image: /img/home.png
      show_sidebar: true


collections:
  authors:
    output: true


